//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.24 at 12:37:20 AM CEST 
//


package com.xml_web_services.domain;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.xml_web_services.domain package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.xml_web_services.domain
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ReserveResponse }
     * 
     */
    public ReserveResponse createReserveResponse() {
        return new ReserveResponse();
    }

    /**
     * Create an instance of {@link GetAllAccomodationCategoriesResponse }
     * 
     */
    public GetAllAccomodationCategoriesResponse createGetAllAccomodationCategoriesResponse() {
        return new GetAllAccomodationCategoriesResponse();
    }

    /**
     * Create an instance of {@link AccomodationCategory }
     * 
     */
    public AccomodationCategory createAccomodationCategory() {
        return new AccomodationCategory();
    }

    /**
     * Create an instance of {@link GetAgentMessages }
     * 
     */
    public GetAgentMessages createGetAgentMessages() {
        return new GetAgentMessages();
    }

    /**
     * Create an instance of {@link GetAgentReviews }
     * 
     */
    public GetAgentReviews createGetAgentReviews() {
        return new GetAgentReviews();
    }

    /**
     * Create an instance of {@link GetAgentMessagesResponse }
     * 
     */
    public GetAgentMessagesResponse createGetAgentMessagesResponse() {
        return new GetAgentMessagesResponse();
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link GetAllAccomodationTypeResponse }
     * 
     */
    public GetAllAccomodationTypeResponse createGetAllAccomodationTypeResponse() {
        return new GetAllAccomodationTypeResponse();
    }

    /**
     * Create an instance of {@link AccomodationType }
     * 
     */
    public AccomodationType createAccomodationType() {
        return new AccomodationType();
    }

    /**
     * Create an instance of {@link SendAccomodationResponse }
     * 
     */
    public SendAccomodationResponse createSendAccomodationResponse() {
        return new SendAccomodationResponse();
    }

    /**
     * Create an instance of {@link SendReservation }
     * 
     */
    public SendReservation createSendReservation() {
        return new SendReservation();
    }

    /**
     * Create an instance of {@link Reservation }
     * 
     */
    public Reservation createReservation() {
        return new Reservation();
    }

    /**
     * Create an instance of {@link GetAllAccomodationTypes }
     * 
     */
    public GetAllAccomodationTypes createGetAllAccomodationTypes() {
        return new GetAllAccomodationTypes();
    }

    /**
     * Create an instance of {@link SendAccomodation }
     * 
     */
    public SendAccomodation createSendAccomodation() {
        return new SendAccomodation();
    }

    /**
     * Create an instance of {@link Accomodation }
     * 
     */
    public Accomodation createAccomodation() {
        return new Accomodation();
    }

    /**
     * Create an instance of {@link ReserveRequest }
     * 
     */
    public ReserveRequest createReserveRequest() {
        return new ReserveRequest();
    }

    /**
     * Create an instance of {@link GetAllAccomodationCategories }
     * 
     */
    public GetAllAccomodationCategories createGetAllAccomodationCategories() {
        return new GetAllAccomodationCategories();
    }

    /**
     * Create an instance of {@link GetAgentReservations }
     * 
     */
    public GetAgentReservations createGetAgentReservations() {
        return new GetAgentReservations();
    }

    /**
     * Create an instance of {@link GetAgentReviewsResponse }
     * 
     */
    public GetAgentReviewsResponse createGetAgentReviewsResponse() {
        return new GetAgentReviewsResponse();
    }

    /**
     * Create an instance of {@link Review }
     * 
     */
    public Review createReview() {
        return new Review();
    }

    /**
     * Create an instance of {@link GetAgentReservationsResponse }
     * 
     */
    public GetAgentReservationsResponse createGetAgentReservationsResponse() {
        return new GetAgentReservationsResponse();
    }

    /**
     * Create an instance of {@link SendReservationResponse }
     * 
     */
    public SendReservationResponse createSendReservationResponse() {
        return new SendReservationResponse();
    }

    /**
     * Create an instance of {@link Agent }
     * 
     */
    public Agent createAgent() {
        return new Agent();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link Images }
     * 
     */
    public Images createImages() {
        return new Images();
    }

    /**
     * Create an instance of {@link PricePlan }
     * 
     */
    public PricePlan createPricePlan() {
        return new PricePlan();
    }

}
