//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.23 at 09:26:50 PM CEST 
//


package com.xml_web_services.domain;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Accomodation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Accomodation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="accomodationId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="capacity">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="0"/>
 *               &lt;pattern value="[0-9]+"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="accomodationType" type="{http://com/xml_web_services/domain}AccomodationType"/>
 *         &lt;element name="accomodationCategory" type="{http://com/xml_web_services/domain}AccomodationCategory"/>
 *         &lt;element name="agent" type="{http://com/xml_web_services/domain}Agent"/>
 *         &lt;element name="images" type="{http://com/xml_web_services/domain}Images" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="pricePlan" type="{http://com/xml_web_services/domain}PricePlan"/>
 *         &lt;element name="street" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="streetNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="parking" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="wifi" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="breakfast" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="hb" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="fb" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="television" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="kitchen" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="bathroom" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="grade" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Accomodation", propOrder = {
    "accomodationId",
    "name",
    "description",
    "capacity",
    "accomodationType",
    "accomodationCategory",
    "agent",
    "images",
    "pricePlan",
    "street",
    "city",
    "country",
    "streetNumber",
    "parking",
    "wifi",
    "breakfast",
    "hb",
    "fb",
    "television",
    "kitchen",
    "bathroom",
    "grade"
})
@Entity
public class Accomodation {

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
    protected long accomodationId;
    @XmlElement(required = true)
    @Column(nullable = false, unique = true)
    protected String name;
    @XmlElement(required = true)
    @Column
    protected String description;
    @Column
    protected int capacity;
    @XmlElement(required = true)
    @ManyToOne
    protected AccomodationType accomodationType;
    @XmlElement(required = true)
    @ManyToOne
    protected AccomodationCategory accomodationCategory;
    @XmlElement(required = true)
    @ManyToOne
    protected Agent agent;
    @OneToMany(fetch = FetchType.EAGER)
    protected List<Images> images;
    @XmlElement(required = true)
    @ManyToOne
    protected PricePlan pricePlan;
    @XmlElement(required = true)
    @Column
    protected String street;
    @XmlElement(required = true)
    @Column
    protected String city;
    @XmlElement(required = true)
    @Column
    protected String country;
    @XmlElement(required = true)
    @Column
    protected String streetNumber;
    @Column
    protected boolean parking;
    @Column
    protected boolean wifi;
    @Column
    protected boolean breakfast;
    @Column
    protected boolean hb;
    @Column
    protected boolean fb;
    @Column
    protected boolean television;
    @Column
    protected boolean kitchen;
    @Column
    protected boolean bathroom;
    @Column
    protected float grade;

    /**
     * Gets the value of the accomodationId property.
     * 
     */
    public long getAccomodationId() {
        return accomodationId;
    }

    /**
     * Sets the value of the accomodationId property.
     * 
     */
    public void setAccomodationId(long value) {
        this.accomodationId = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the capacity property.
     * 
     */
    public int getCapacity() {
        return capacity;
    }

    /**
     * Sets the value of the capacity property.
     * 
     */
    public void setCapacity(int value) {
        this.capacity = value;
    }

    /**
     * Gets the value of the accomodationType property.
     * 
     * @return
     *     possible object is
     *     {@link AccomodationType }
     *     
     */
    public AccomodationType getAccomodationType() {
        return accomodationType;
    }

    /**
     * Sets the value of the accomodationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccomodationType }
     *     
     */
    public void setAccomodationType(AccomodationType value) {
        this.accomodationType = value;
    }

    /**
     * Gets the value of the accomodationCategory property.
     * 
     * @return
     *     possible object is
     *     {@link AccomodationCategory }
     *     
     */
    public AccomodationCategory getAccomodationCategory() {
        return accomodationCategory;
    }

    /**
     * Sets the value of the accomodationCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccomodationCategory }
     *     
     */
    public void setAccomodationCategory(AccomodationCategory value) {
        this.accomodationCategory = value;
    }

    /**
     * Gets the value of the agent property.
     * 
     * @return
     *     possible object is
     *     {@link Agent }
     *     
     */
    public Agent getAgent() {
        return agent;
    }

    /**
     * Sets the value of the agent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Agent }
     *     
     */
    public void setAgent(Agent value) {
        this.agent = value;
    }

    /**
     * Gets the value of the images property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the images property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getImages().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Images }
     * 
     * 
     */
    public List<Images> getImages() {
        if (images == null) {
            images = new ArrayList<Images>();
        }
        return this.images;
    }

    /**
     * Gets the value of the pricePlan property.
     * 
     * @return
     *     possible object is
     *     {@link PricePlan }
     *     
     */
    public PricePlan getPricePlan() {
        return pricePlan;
    }

    /**
     * Sets the value of the pricePlan property.
     * 
     * @param value
     *     allowed object is
     *     {@link PricePlan }
     *     
     */
    public void setPricePlan(PricePlan value) {
        this.pricePlan = value;
    }

    /**
     * Gets the value of the street property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreet() {
        return street;
    }

    /**
     * Sets the value of the street property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreet(String value) {
        this.street = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the streetNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreetNumber() {
        return streetNumber;
    }

    /**
     * Sets the value of the streetNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreetNumber(String value) {
        this.streetNumber = value;
    }

    /**
     * Gets the value of the parking property.
     * 
     */
    public boolean isParking() {
        return parking;
    }

    /**
     * Sets the value of the parking property.
     * 
     */
    public void setParking(boolean value) {
        this.parking = value;
    }

    /**
     * Gets the value of the wifi property.
     * 
     */
    public boolean isWifi() {
        return wifi;
    }

    /**
     * Sets the value of the wifi property.
     * 
     */
    public void setWifi(boolean value) {
        this.wifi = value;
    }

    /**
     * Gets the value of the breakfast property.
     * 
     */
    public boolean isBreakfast() {
        return breakfast;
    }

    /**
     * Sets the value of the breakfast property.
     * 
     */
    public void setBreakfast(boolean value) {
        this.breakfast = value;
    }

    /**
     * Gets the value of the hb property.
     * 
     */
    public boolean isHb() {
        return hb;
    }

    /**
     * Sets the value of the hb property.
     * 
     */
    public void setHb(boolean value) {
        this.hb = value;
    }

    /**
     * Gets the value of the fb property.
     * 
     */
    public boolean isFb() {
        return fb;
    }

    /**
     * Sets the value of the fb property.
     * 
     */
    public void setFb(boolean value) {
        this.fb = value;
    }

    /**
     * Gets the value of the television property.
     * 
     */
    public boolean isTelevision() {
        return television;
    }

    /**
     * Sets the value of the television property.
     * 
     */
    public void setTelevision(boolean value) {
        this.television = value;
    }

    /**
     * Gets the value of the kitchen property.
     * 
     */
    public boolean isKitchen() {
        return kitchen;
    }

    /**
     * Sets the value of the kitchen property.
     * 
     */
    public void setKitchen(boolean value) {
        this.kitchen = value;
    }

    /**
     * Gets the value of the bathroom property.
     * 
     */
    public boolean isBathroom() {
        return bathroom;
    }

    /**
     * Sets the value of the bathroom property.
     * 
     */
    public void setBathroom(boolean value) {
        this.bathroom = value;
    }

    /**
     * Gets the value of the grade property.
     * 
     */
    public float getGrade() {
        return grade;
    }

    /**
     * Sets the value of the grade property.
     * 
     */
    public void setGrade(float value) {
        this.grade = value;
    }

}
