//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.23 at 09:26:50 PM CEST 
//


package com.xml_web_services.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Message complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Message">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="messageId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="messagText" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="readed" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="replyId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="agent" type="{http://com/xml_web_services/domain}Agent"/>
 *         &lt;element name="user" type="{http://com/xml_web_services/domain}User"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Message", propOrder = {
    "messageId",
    "messagText",
    "readed",
    "replyId",
    "agent",
    "user"
})
@Entity
public class Message {

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
    protected long messageId;
    @XmlElement(required = true)
    @Column(nullable = false)
    protected String messagText;
    @Column
    protected boolean readed=false;
    @Column
    protected long replyId;
    @XmlElement(required = true)
    @ManyToOne
    protected Agent agent;
    @XmlElement(required = true)
    @ManyToOne
    protected User user;

    /**
     * Gets the value of the messageId property.
     * 
     */
    public long getMessageId() {
        return messageId;
    }

    /**
     * Sets the value of the messageId property.
     * 
     */
    public void setMessageId(long value) {
        this.messageId = value;
    }

    /**
     * Gets the value of the messagText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessagText() {
        return messagText;
    }

    /**
     * Sets the value of the messagText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessagText(String value) {
        this.messagText = value;
    }

    /**
     * Gets the value of the readed property.
     * 
     */
    public boolean isReaded() {
        return readed;
    }

    /**
     * Sets the value of the readed property.
     * 
     */
    public void setReaded(boolean value) {
        this.readed = value;
    }

    /**
     * Gets the value of the replyId property.
     * 
     */
    public long getReplyId() {
        return replyId;
    }

    /**
     * Sets the value of the replyId property.
     * 
     */
    public void setReplyId(long value) {
        this.replyId = value;
    }

    /**
     * Gets the value of the agent property.
     * 
     * @return
     *     possible object is
     *     {@link Agent }
     *     
     */
    public Agent getAgent() {
        return agent;
    }

    /**
     * Sets the value of the agent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Agent }
     *     
     */
    public void setAgent(Agent value) {
        this.agent = value;
    }

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link User }
     *     
     */
    public User getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link User }
     *     
     */
    public void setUser(User value) {
        this.user = value;
    }

}
